hardware_params:
  n_chambers: 6

  pmax:
    - 1.36
    - 1.36
    - 1.36
    - 1.36
    - 1.36
    - 1.36

  pmin:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  digit_max:
    - 159
    - 159
    - 159
    - 159
    - 159
    - 159

  digit_min:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0


    