hardware_params:
  n_chambers: 7

  pmax:
    - 4.0
    - 4.0
    - 4.0
    - 4.0
    - 4.0
    - 4.0
    - 4.0

  pmin:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  digit_max:
    - 36
    - 36
    - 36
    - 36
    - 36
    - 36
    - 36

  digit_min:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0


    