hardware_params:
  pmax:
    - 1.68
    - 1.68
    - 1.68
    - 1.08
    - 1.68
    - 1.68
    - 4.4
    - 4.4
    - 1.02

  pmin:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  digit_max:
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 4095

  digit_min:
    - 10
    - 10
    - 10
    - 15
    - 10
    - 10
    - 10
    - 10
    - 50


    