hardware_params:
  n_chambers: 6

  pmax:
    - 5.4
    - 5.4
    - 5.4
    - 5.4
    - 5.4
    - 5.4

  pmin:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  digit_max:
    - 125
    - 125
    - 125
    - 125
    - 125
    - 125

  digit_min:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0


    